#!/bin/sh
#
# messagebus:   The D-BUS systemwide message bus
#
# chkconfig: 345 97 03
# description:  This is a daemon which broadcasts notifications of system events \
#               and other messages. See http://www.freedesktop.org/software/dbus/
#
# processname: dbus-daemon
# pidfile: //var/run/messagebus.pid
#

# Sanity checks.
[ -x //bin/dbus-daemon ] || exit 0

# Source function library.
. //etc/rc.d/init.d/functions

# so we can rearrange this easily
processname=dbus-daemon
servicename=messagebus

RETVAL=0

start() {
    echo -n $"Starting system message bus: "
    if [ -x //bin/dbus-uuidgen ] ; then
        //bin/dbus-uuidgen --ensure
    fi

    daemon --check $servicename $processname --system
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch //var/lock/subsys/$servicename
}

stop() {
    echo -n $"Stopping system message bus: "

    ## we don't want to kill all the per-user $processname, we want
    ## to use the pid file *only*; because we use the fake nonexistent 
    ## program name "$servicename" that should be safe-ish
    killproc $servicename -TERM
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f //var/lock/subsys/$servicename
        rm -f //var/run/messagebus.pid
    fi
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $processname
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        if [ -f //var/lock/subsys/$servicename ]; then
            stop
            start
        fi
        ;;
    reload)
        echo "Message bus can't reload its configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        ;;
esac
exit $RETVAL
