/* soapServerLib.c
   Generated by gSOAP 2.8.0 from cwmp-1-0.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

/** Use this file in your project build instead of the two files soapC.c and soapServer.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "soapC.c"
#include "soapServer.c"

/* End of soapServerLib.c */
