/* soapStub.h
   Generated by gSOAP 2.8.0 from cwmp-1-0.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (13)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

#ifndef SOAP_TYPE__cwmp__FaultStruct_FaultCode
#define SOAP_TYPE__cwmp__FaultStruct_FaultCode (21)
/* cwmp:FaultStruct-FaultCode */
enum _cwmp__FaultStruct_FaultCode {_cwmp__FaultStruct_FaultCode__0 = 0, _cwmp__FaultStruct_FaultCode__9001 = 9001, _cwmp__FaultStruct_FaultCode__9002 = 9002, _cwmp__FaultStruct_FaultCode__9003 = 9003, _cwmp__FaultStruct_FaultCode__9004 = 9004, _cwmp__FaultStruct_FaultCode__9005 = 9005, _cwmp__FaultStruct_FaultCode__9006 = 9006, _cwmp__FaultStruct_FaultCode__9007 = 9007, _cwmp__FaultStruct_FaultCode__9008 = 9008, _cwmp__FaultStruct_FaultCode__9009 = 9009, _cwmp__FaultStruct_FaultCode__9010 = 9010, _cwmp__FaultStruct_FaultCode__9011 = 9011, _cwmp__FaultStruct_FaultCode__9012 = 9012};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__cwmp__SetParameterAttributesStruct_Notification (27)
/* cwmp:SetParameterAttributesStruct-Notification */
enum _cwmp__SetParameterAttributesStruct_Notification {_cwmp__SetParameterAttributesStruct_Notification__0 = 0, _cwmp__SetParameterAttributesStruct_Notification__1 = 1, _cwmp__SetParameterAttributesStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification
#define SOAP_TYPE__cwmp__ParameterAttributeStruct_Notification (31)
/* cwmp:ParameterAttributeStruct-Notification */
enum _cwmp__ParameterAttributeStruct_Notification {_cwmp__ParameterAttributeStruct_Notification__0 = 0, _cwmp__ParameterAttributeStruct_Notification__1 = 1, _cwmp__ParameterAttributeStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__QueuedTransferStruct_State
#define SOAP_TYPE__cwmp__QueuedTransferStruct_State (33)
/* cwmp:QueuedTransferStruct-State */
enum _cwmp__QueuedTransferStruct_State {_cwmp__QueuedTransferStruct_State__1 = 1, _cwmp__QueuedTransferStruct_State__2 = 2, _cwmp__QueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_State
#define SOAP_TYPE__cwmp__OptionStruct_State (35)
/* cwmp:OptionStruct-State */
enum _cwmp__OptionStruct_State {_cwmp__OptionStruct_State__0 = 0, _cwmp__OptionStruct_State__1 = 1, _cwmp__OptionStruct_State__2 = 2, _cwmp__OptionStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_Mode
#define SOAP_TYPE__cwmp__OptionStruct_Mode (36)
/* cwmp:OptionStruct-Mode */
enum _cwmp__OptionStruct_Mode {_cwmp__OptionStruct_Mode__0 = 0, _cwmp__OptionStruct_Mode__1 = 1, _cwmp__OptionStruct_Mode__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp__OptionStruct_IsTransferable (39)
/* cwmp:OptionStruct-IsTransferable */
enum _cwmp__OptionStruct_IsTransferable {_cwmp__OptionStruct_IsTransferable__0 = 0, _cwmp__OptionStruct_IsTransferable__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp__SetParameterValuesResponse_Status (52)
/* cwmp:SetParameterValuesResponse-Status */
enum _cwmp__SetParameterValuesResponse_Status {_cwmp__SetParameterValuesResponse_Status__0 = 0, _cwmp__SetParameterValuesResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse_Status
#define SOAP_TYPE__cwmp__AddObjectResponse_Status (71)
/* cwmp:AddObjectResponse-Status */
enum _cwmp__AddObjectResponse_Status {_cwmp__AddObjectResponse_Status__0 = 0, _cwmp__AddObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp__DeleteObjectResponse_Status (74)
/* cwmp:DeleteObjectResponse-Status */
enum _cwmp__DeleteObjectResponse_Status {_cwmp__DeleteObjectResponse_Status__0 = 0, _cwmp__DeleteObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse_Status
#define SOAP_TYPE__cwmp__DownloadResponse_Status (77)
/* cwmp:DownloadResponse-Status */
enum _cwmp__DownloadResponse_Status {_cwmp__DownloadResponse_Status__0 = 0, _cwmp__DownloadResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse_Status
#define SOAP_TYPE__cwmp__UploadResponse_Status (96)
/* cwmp:UploadResponse-Status */
enum _cwmp__UploadResponse_Status {_cwmp__UploadResponse_Status__0 = 0, _cwmp__UploadResponse_Status__1 = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (8)
/* Base64 schema type: */
struct SOAP_ENC__base64
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (15)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	char *cwmp__ID;	/* mustUnderstand */
};
#endif

#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (20)
/* cwmp:FaultStruct */
struct cwmp__FaultStruct
{
	enum _cwmp__FaultStruct_FaultCode FaultCode;	/* required element of type cwmp:FaultStruct-FaultCode */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (22)
/* cwmp:DeviceIdStruct */
struct cwmp__DeviceIdStruct
{
	char *Manufacturer;	/* required element of type xsd:string */
	char *OUI;	/* required element of type xsd:string */
	char *ProductClass;	/* required element of type xsd:string */
	char *SerialNumber;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (23)
/* cwmp:EventStruct */
struct cwmp__EventStruct
{
	char *EventCode;	/* required element of type xsd:string */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (24)
/* cwmp:ParameterValueStruct */
struct cwmp__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:anySimpleType */
	int Type;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (25)
/* cwmp:ParameterInfoStruct */
struct cwmp__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean Writable;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (26)
/* cwmp:SetParameterAttributesStruct */
struct cwmp__SetParameterAttributesStruct
{
	char *Name;	/* optional element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum _cwmp__SetParameterAttributesStruct_Notification Notification;	/* required element of type cwmp:SetParameterAttributesStruct-Notification */
	enum xsd__boolean AccessListChange;	/* required element of type xsd:boolean */
	struct AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (30)
/* cwmp:ParameterAttributeStruct */
struct cwmp__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum _cwmp__ParameterAttributeStruct_Notification Notification;	/* required element of type cwmp:ParameterAttributeStruct-Notification */
	struct AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__QueuedTransferStruct
#define SOAP_TYPE_cwmp__QueuedTransferStruct (32)
/* cwmp:QueuedTransferStruct */
struct cwmp__QueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	enum _cwmp__QueuedTransferStruct_State State;	/* required element of type cwmp:QueuedTransferStruct-State */
};
#endif

#ifndef SOAP_TYPE_cwmp__OptionStruct
#define SOAP_TYPE_cwmp__OptionStruct (34)
/* cwmp:OptionStruct */
struct cwmp__OptionStruct
{
	char *OptionName;	/* required element of type xsd:string */
	unsigned int VoucherSN;	/* required element of type xsd:unsignedInt */
	enum _cwmp__OptionStruct_State State;	/* required element of type cwmp:OptionStruct-State */
	enum _cwmp__OptionStruct_Mode Mode;	/* required element of type cwmp:OptionStruct-Mode */
	time_t StartDate;	/* required element of type xsd:dateTime */
	time_t *ExpirationDate;	/* optional element of type xsd:dateTime */
	enum _cwmp__OptionStruct_IsTransferable IsTransferable;	/* required element of type cwmp:OptionStruct-IsTransferable */
};
#endif

#ifndef SOAP_TYPE_cwmp__ArgStruct
#define SOAP_TYPE_cwmp__ArgStruct (40)
/* cwmp:ArgStruct */
struct cwmp__ArgStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (42)
/* cwmp:Fault-SetParameterValuesFault */
struct _cwmp__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (41)
/* cwmp:Fault */
struct _cwmp__Fault
{
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _cwmp__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type cwmp:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (44)
/* cwmp:GetRPCMethods */
struct _cwmp__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (45)
/* cwmp:GetRPCMethodsResponse */
struct _cwmp__GetRPCMethodsResponse
{
	struct MethodList *MethodList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (48)
/* cwmp:SetParameterValues */
struct _cwmp__SetParameterValues
{
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (51)
/* cwmp:SetParameterValuesResponse */
struct _cwmp__SetParameterValuesResponse
{
	enum _cwmp__SetParameterValuesResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (53)
/* cwmp:GetParameterValues */
struct _cwmp__GetParameterValues
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (56)
/* cwmp:GetParameterValuesResponse */
struct _cwmp__GetParameterValuesResponse
{
	struct ParameterValueList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (57)
/* cwmp:GetParameterNames */
struct _cwmp__GetParameterNames
{
	char *ParameterPath;	/* optional element of type xsd:string */
	enum xsd__boolean NextLevel;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (58)
/* cwmp:GetParameterNamesResponse */
struct _cwmp__GetParameterNamesResponse
{
	struct ParameterInfoList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (61)
/* cwmp:SetParameterAttributes */
struct _cwmp__SetParameterAttributes
{
	struct SetParameterAttributesList *ParameterList;	/* required element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (64)
/* cwmp:SetParameterAttributesResponse */
struct _cwmp__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (65)
/* cwmp:GetParameterAttributes */
struct _cwmp__GetParameterAttributes
{
	struct ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (66)
/* cwmp:GetParameterAttributesResponse */
struct _cwmp__GetParameterAttributesResponse
{
	struct ParameterAttributeList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (69)
/* cwmp:AddObject */
struct _cwmp__AddObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (70)
/* cwmp:AddObjectResponse */
struct _cwmp__AddObjectResponse
{
	unsigned int InstanceNumber;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
	enum _cwmp__AddObjectResponse_Status Status;	/* required element of type cwmp:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (72)
/* cwmp:DeleteObject */
struct _cwmp__DeleteObject
{
	char *ObjectName;	/* required element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (73)
/* cwmp:DeleteObjectResponse */
struct _cwmp__DeleteObjectResponse
{
	enum _cwmp__DeleteObjectResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (75)
/* cwmp:Download */
struct _cwmp__Download
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *SuccessURL;	/* required element of type xsd:string */
	char *FailureURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (76)
/* cwmp:DownloadResponse */
struct _cwmp__DownloadResponse
{
	enum _cwmp__DownloadResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:DownloadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (78)
/* cwmp:Reboot */
struct _cwmp__Reboot
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (79)
/* cwmp:RebootResponse */
struct _cwmp__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfers
#define SOAP_TYPE__cwmp__GetQueuedTransfers (80)
/* cwmp:GetQueuedTransfers */
struct _cwmp__GetQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp__GetQueuedTransfersResponse (81)
/* cwmp:GetQueuedTransfersResponse */
struct _cwmp__GetQueuedTransfersResponse
{
	struct TransferList *TransferList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (84)
/* cwmp:ScheduleInform */
struct _cwmp__ScheduleInform
{
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (85)
/* cwmp:ScheduleInformResponse */
struct _cwmp__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchers
#define SOAP_TYPE__cwmp__SetVouchers (86)
/* cwmp:SetVouchers */
struct _cwmp__SetVouchers
{
	struct VoucherList *VoucherList;	/* required element of type ArrayOfbase64 */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetVouchersResponse
#define SOAP_TYPE__cwmp__SetVouchersResponse (89)
/* cwmp:SetVouchersResponse */
struct _cwmp__SetVouchersResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptions
#define SOAP_TYPE__cwmp__GetOptions (90)
/* cwmp:GetOptions */
struct _cwmp__GetOptions
{
	char *OptionName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetOptionsResponse
#define SOAP_TYPE__cwmp__GetOptionsResponse (91)
/* cwmp:GetOptionsResponse */
struct _cwmp__GetOptionsResponse
{
	struct OptionList *OptionList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfOptionStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (94)
/* cwmp:Upload */
struct _cwmp__Upload
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (95)
/* cwmp:UploadResponse */
struct _cwmp__UploadResponse
{
	enum _cwmp__UploadResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:UploadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (97)
/* cwmp:FactoryReset */
struct _cwmp__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (98)
/* cwmp:FactoryResetResponse */
struct _cwmp__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (99)
/* cwmp:Inform */
struct _cwmp__Inform
{
	struct cwmp__DeviceIdStruct *DeviceId;	/* required element of type cwmp:DeviceIdStruct */
	struct EventList *Event;	/* required element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	time_t CurrentTime;	/* required element of type xsd:dateTime */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (103)
/* cwmp:InformResponse */
struct _cwmp__InformResponse
{
	unsigned int MaxEnvelopes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (104)
/* cwmp:TransferComplete */
struct _cwmp__TransferComplete
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (106)
/* cwmp:TransferCompleteResponse */
struct _cwmp__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Kicked
#define SOAP_TYPE__cwmp__Kicked (107)
/* cwmp:Kicked */
struct _cwmp__Kicked
{
	char *Command;	/* required element of type xsd:string */
	char *Referer;	/* required element of type xsd:string */
	char *Arg;	/* required element of type xsd:string */
	char *Next;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__KickedResponse
#define SOAP_TYPE__cwmp__KickedResponse (108)
/* cwmp:KickedResponse */
struct _cwmp__KickedResponse
{
	char *NextURL;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownload
#define SOAP_TYPE__cwmp__RequestDownload (109)
/* cwmp:RequestDownload */
struct _cwmp__RequestDownload
{
	char *FileType;	/* required element of type xsd:string */
	struct FileTypeArg *FileTypeArg;	/* required element of type ArrayOfArgStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__RequestDownloadResponse
#define SOAP_TYPE__cwmp__RequestDownloadResponse (112)
/* cwmp:RequestDownloadResponse */
struct _cwmp__RequestDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_MethodList
#define SOAP_TYPE_MethodList (46)
/* SOAP encoded array of xsd:string schema type: */
struct MethodList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_EventList
#define SOAP_TYPE_EventList (101)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct EventList
{
	struct cwmp__EventStruct *__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (49)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct ParameterValueList
{
	struct cwmp__ParameterValueStruct *__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (59)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
struct ParameterInfoList
{
	struct cwmp__ParameterInfoStruct *__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (54)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (28)
/* SOAP encoded array of xsd:string schema type: */
struct AccessList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (62)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList
{
	struct cwmp__SetParameterAttributesStruct *__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (67)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct ParameterAttributeList
{
	struct cwmp__ParameterAttributeStruct *__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_TransferList
#define SOAP_TYPE_TransferList (82)
/* SOAP encoded array of cwmp:QueuedTransferStruct schema type: */
struct TransferList
{
	struct cwmp__QueuedTransferStruct *__ptrQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_VoucherList
#define SOAP_TYPE_VoucherList (87)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct VoucherList
{
	struct SOAP_ENC__base64 *__ptrbase64;
	int __size;
};
#endif

#ifndef SOAP_TYPE_OptionList
#define SOAP_TYPE_OptionList (92)
/* SOAP encoded array of cwmp:OptionStruct schema type: */
struct OptionList
{
	struct cwmp__OptionStruct *__ptrOptionStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_FileTypeArg
#define SOAP_TYPE_FileTypeArg (110)
/* SOAP encoded array of cwmp:ArgStruct schema type: */
struct FileTypeArg
{
	struct cwmp__ArgStruct *__ptrArgStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__cwmp__ID
#define SOAP_TYPE__cwmp__ID (123)
/* Primitive cwmp:ID schema type: */
struct _cwmp__ID
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type SOAP-ENV:mustUnderstand */
};
#endif

#ifndef SOAP_TYPE__cwmp__HoldRequests
#define SOAP_TYPE__cwmp__HoldRequests (124)
/* Primitive cwmp:HoldRequests schema type: */
struct _cwmp__HoldRequests
{
	enum xsd__boolean __item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type SOAP-ENV:mustUnderstand */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetRPCMethods
#define SOAP_TYPE_cwmp__GetRPCMethods (127)
/* cwmp:GetRPCMethods */
struct cwmp__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterValues
#define SOAP_TYPE_cwmp__SetParameterValues (131)
/* cwmp:SetParameterValues */
struct cwmp__SetParameterValues
{
	struct _cwmp__SetParameterValues *__SetParameterValues;
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterValues
#define SOAP_TYPE_cwmp__GetParameterValues (135)
/* cwmp:GetParameterValues */
struct cwmp__GetParameterValues
{
	struct _cwmp__GetParameterValues *__GetParameterValues;
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterNames
#define SOAP_TYPE_cwmp__GetParameterNames (139)
/* cwmp:GetParameterNames */
struct cwmp__GetParameterNames
{
	struct _cwmp__GetParameterNames *__GetParameterNames;
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributes
#define SOAP_TYPE_cwmp__SetParameterAttributes (143)
/* cwmp:SetParameterAttributes */
struct cwmp__SetParameterAttributes
{
	struct _cwmp__SetParameterAttributes *__SetParameterAttributes;
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterAttributes
#define SOAP_TYPE_cwmp__GetParameterAttributes (147)
/* cwmp:GetParameterAttributes */
struct cwmp__GetParameterAttributes
{
	struct _cwmp__GetParameterAttributes *__GetParameterAttributes;
};
#endif

#ifndef SOAP_TYPE_cwmp__AddObject
#define SOAP_TYPE_cwmp__AddObject (151)
/* cwmp:AddObject */
struct cwmp__AddObject
{
	struct _cwmp__AddObject *__AddObject;
};
#endif

#ifndef SOAP_TYPE_cwmp__DeleteObject
#define SOAP_TYPE_cwmp__DeleteObject (155)
/* cwmp:DeleteObject */
struct cwmp__DeleteObject
{
	struct _cwmp__DeleteObject *__DeleteObject;
};
#endif

#ifndef SOAP_TYPE_cwmp__Download
#define SOAP_TYPE_cwmp__Download (159)
/* cwmp:Download */
struct cwmp__Download
{
	struct _cwmp__Download *__Download;
};
#endif

#ifndef SOAP_TYPE_cwmp__Reboot
#define SOAP_TYPE_cwmp__Reboot (163)
/* cwmp:Reboot */
struct cwmp__Reboot
{
	struct _cwmp__Reboot *__Reboot;
};
#endif

#ifndef SOAP_TYPE_cwmp__GetQueuedTransfers
#define SOAP_TYPE_cwmp__GetQueuedTransfers (167)
/* cwmp:GetQueuedTransfers */
struct cwmp__GetQueuedTransfers
{
	struct _cwmp__GetQueuedTransfers *__GetQueuedTransfers;
};
#endif

#ifndef SOAP_TYPE_cwmp__ScheduleInform
#define SOAP_TYPE_cwmp__ScheduleInform (171)
/* cwmp:ScheduleInform */
struct cwmp__ScheduleInform
{
	struct _cwmp__ScheduleInform *__ScheduleInform;
};
#endif

#ifndef SOAP_TYPE_cwmp__SetVouchers
#define SOAP_TYPE_cwmp__SetVouchers (175)
/* cwmp:SetVouchers */
struct cwmp__SetVouchers
{
	struct _cwmp__SetVouchers *__SetVouchers;
};
#endif

#ifndef SOAP_TYPE_cwmp__GetOptions
#define SOAP_TYPE_cwmp__GetOptions (179)
/* cwmp:GetOptions */
struct cwmp__GetOptions
{
	struct _cwmp__GetOptions *__GetOptions;
};
#endif

#ifndef SOAP_TYPE_cwmp__Upload
#define SOAP_TYPE_cwmp__Upload (183)
/* cwmp:Upload */
struct cwmp__Upload
{
	struct _cwmp__Upload *__Upload;
};
#endif

#ifndef SOAP_TYPE_cwmp__FactoryReset
#define SOAP_TYPE_cwmp__FactoryReset (187)
/* cwmp:FactoryReset */
struct cwmp__FactoryReset
{
	struct _cwmp__FactoryReset *__FactoryReset;
};
#endif

#ifndef SOAP_TYPE_cwmp__Inform
#define SOAP_TYPE_cwmp__Inform (191)
/* cwmp:Inform */
struct cwmp__Inform
{
	struct _cwmp__Inform *__Inform;
};
#endif

#ifndef SOAP_TYPE_cwmp__TransferComplete
#define SOAP_TYPE_cwmp__TransferComplete (195)
/* cwmp:TransferComplete */
struct cwmp__TransferComplete
{
	struct _cwmp__TransferComplete *__TransferComplete;
};
#endif

#ifndef SOAP_TYPE_cwmp__Kicked
#define SOAP_TYPE_cwmp__Kicked (199)
/* cwmp:Kicked */
struct cwmp__Kicked
{
	struct _cwmp__Kicked *__Kicked;
};
#endif

#ifndef SOAP_TYPE_cwmp__RequestDownload
#define SOAP_TYPE_cwmp__RequestDownload (203)
/* cwmp:RequestDownload */
struct cwmp__RequestDownload
{
	struct _cwmp__RequestDownload *__RequestDownload;
};
#endif

#ifndef SOAP_TYPE_cwmp__PostNull
#define SOAP_TYPE_cwmp__PostNull (206)
/* cwmp:PostNull */
struct cwmp__PostNull
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (207)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (209)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (211)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (212)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
typedef char *xsd__string;
#endif

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (12)
typedef char *xsd__anySimpleType;
#endif

#ifndef SOAP_TYPE__SOAP_ENV__mustUnderstand
#define SOAP_TYPE__SOAP_ENV__mustUnderstand (14)
typedef char *_SOAP_ENV__mustUnderstand;
#endif

#ifndef SOAP_TYPE_cwmp__FaultCodeType
#define SOAP_TYPE_cwmp__FaultCodeType (16)
typedef char *cwmp__FaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (17)
typedef char *cwmp__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (18)
typedef char *cwmp__CommandKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (19)
typedef char *cwmp__ObjectNameType;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 cwmp__GetRPCMethods(struct soap*, struct _cwmp__GetRPCMethodsResponse *__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__SetParameterValues(struct soap*, struct _cwmp__SetParameterValues *__SetParameterValues, struct _cwmp__SetParameterValuesResponse *__SetParameterValuesReponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__GetParameterValues(struct soap*, struct _cwmp__GetParameterValues *__GetParameterValues, struct _cwmp__GetParameterValuesResponse *__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__GetParameterNames(struct soap*, struct _cwmp__GetParameterNames *__GetParameterNames, struct _cwmp__GetParameterNamesResponse *__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__SetParameterAttributes(struct soap*, struct _cwmp__SetParameterAttributes *__SetParameterAttributes, struct _cwmp__SetParameterAttributesResponse *__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__GetParameterAttributes(struct soap*, struct _cwmp__GetParameterAttributes *__GetParameterAttributes, struct _cwmp__GetParameterAttributesResponse *__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__AddObject(struct soap*, struct _cwmp__AddObject *__AddObject, struct _cwmp__AddObjectResponse *__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__DeleteObject(struct soap*, struct _cwmp__DeleteObject *__DeleteObject, struct _cwmp__DeleteObjectResponse *__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__Download(struct soap*, struct _cwmp__Download *__Download, struct _cwmp__DownloadResponse *__DownloadResponse);
#ifdef AEI_TR69
SOAP_FMAC5 int SOAP_FMAC6 cwmp__Download_Upgrade(struct soap*, struct _cwmp__Download *__Download, struct _cwmp__DownloadResponse *__DownloadResponse);
#endif
SOAP_FMAC5 int SOAP_FMAC6 cwmp__Reboot(struct soap*, struct _cwmp__Reboot *__Reboot, struct _cwmp__RebootResponse *__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__GetQueuedTransfers(struct soap*, struct _cwmp__GetQueuedTransfers *__GetQueuedTransfers, struct _cwmp__GetQueuedTransfersResponse *__GetQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__ScheduleInform(struct soap*, struct _cwmp__ScheduleInform *__ScheduleInform, struct _cwmp__ScheduleInformResponse *__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__SetVouchers(struct soap*, struct _cwmp__SetVouchers *__SetVouchers, struct _cwmp__SetVouchersResponse *__SetVouchersResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__GetOptions(struct soap*, struct _cwmp__GetOptions *__GetOptions, struct _cwmp__GetOptionsResponse *__GetOptionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__Upload(struct soap*, struct _cwmp__Upload *__Upload, struct _cwmp__UploadResponse *__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__FactoryReset(struct soap*, struct _cwmp__FactoryReset *__FactoryReset, struct _cwmp__FactoryResetResponse *__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__Inform(struct soap*, struct _cwmp__Inform *__Inform, struct _cwmp__InformResponse *__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__TransferComplete(struct soap*, struct _cwmp__TransferComplete *__TransferComplete, struct _cwmp__TransferCompleteResponse *__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__Kicked(struct soap*, struct _cwmp__Kicked *__Kicked, struct _cwmp__KickedResponse *__KickedResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__RequestDownload(struct soap*, struct _cwmp__RequestDownload *__RequestDownload, struct _cwmp__RequestDownloadResponse *__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 cwmp__PostNull(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetRPCMethods(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__DeleteObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Download(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Reboot(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetQueuedTransfers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__ScheduleInform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetVouchers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetOptions(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Upload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__FactoryReset(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__TransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Kicked(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__RequestDownload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__PostNull(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetRPCMethodsResponse *__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterValues *__SetParameterValues, struct _cwmp__SetParameterValuesResponse *__SetParameterValuesReponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterValues *__GetParameterValues, struct _cwmp__GetParameterValuesResponse *__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterNames *__GetParameterNames, struct _cwmp__GetParameterNamesResponse *__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterAttributes *__SetParameterAttributes, struct _cwmp__SetParameterAttributesResponse *__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterAttributes *__GetParameterAttributes, struct _cwmp__GetParameterAttributesResponse *__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AddObject *__AddObject, struct _cwmp__AddObjectResponse *__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DeleteObject *__DeleteObject, struct _cwmp__DeleteObjectResponse *__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Download *__Download, struct _cwmp__DownloadResponse *__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Reboot *__Reboot, struct _cwmp__RebootResponse *__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetQueuedTransfers *__GetQueuedTransfers, struct _cwmp__GetQueuedTransfersResponse *__GetQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__ScheduleInform *__ScheduleInform, struct _cwmp__ScheduleInformResponse *__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetVouchers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetVouchers *__SetVouchers, struct _cwmp__SetVouchersResponse *__SetVouchersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetOptions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetOptions *__GetOptions, struct _cwmp__GetOptionsResponse *__GetOptionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Upload *__Upload, struct _cwmp__UploadResponse *__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__FactoryReset *__FactoryReset, struct _cwmp__FactoryResetResponse *__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Inform *__Inform, struct _cwmp__InformResponse *__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__TransferComplete *__TransferComplete, struct _cwmp__TransferCompleteResponse *__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Kicked *__Kicked, struct _cwmp__KickedResponse *__KickedResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__RequestDownload *__RequestDownload, struct _cwmp__RequestDownloadResponse *__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_send_cwmp__PostNull(struct soap *soap, const char *soap_endpoint, const char *soap_action);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_cwmp__PostNull(struct soap *soap, struct cwmp__PostNull *_param_1);


#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
