/* soapServer.c
   Generated by gSOAP 2.8.0 from cwmp-1-0.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.0 2011-04-20 02:51:34 GMT")

#include "tr69_internal.h"


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
  unsigned int k = soap->max_keep_alive;

  do
  {
    soap_begin(soap);

    if (soap->max_keep_alive > 0 && !--k)
      soap->keep_alive = 0;

    if (soap_begin_recv(soap)) {
      if (soap->error < SOAP_STOP) {
        soap->keep_alive = 0;
        return SOAP_OK;
      }

      continue;
    }

    if (soap->status == 204) {
        printf("recv SOAP END 204\n");
        soap->keep_alive = 0;
        return SOAP_OK;
    }

    if (soap_envelope_begin_in(soap)
        || soap_recv_header(soap)
        || soap_body_begin_in(soap)
        || soap_serve_request(soap)
        || (soap->fserveloop && soap->fserveloop(soap)))
    {
      continue;
    }

#ifdef AEI_TR69
    if (soap->keep_alive == -1)    {
      fprintf(stderr, "disable EnableCWMP, tr69 quit\n");
      exit(0);
    }
#endif        

  } while (soap->keep_alive);

  return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
        soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetRPCMethods"))
		return soap_serve_cwmp__GetRPCMethods(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterValues"))
		return soap_serve_cwmp__SetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterValues"))
		return soap_serve_cwmp__GetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterNames"))
		return soap_serve_cwmp__GetParameterNames(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterAttributes"))
		return soap_serve_cwmp__SetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterAttributes"))
		return soap_serve_cwmp__GetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AddObject"))
		return soap_serve_cwmp__AddObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:DeleteObject"))
		return soap_serve_cwmp__DeleteObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Download"))
		return soap_serve_cwmp__Download(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Reboot"))
		return soap_serve_cwmp__Reboot(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetQueuedTransfers"))
		return soap_serve_cwmp__GetQueuedTransfers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:ScheduleInform"))
		return soap_serve_cwmp__ScheduleInform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetVouchers"))
		return soap_serve_cwmp__SetVouchers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetOptions"))
#if 0
		return soap_serve_cwmp__GetOptions(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Upload"))
#endif
		return soap_serve_cwmp__Upload(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:FactoryReset"))
		return soap_serve_cwmp__FactoryReset(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Inform"))
		return soap_serve_cwmp__Inform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:TransferComplete"))
		return soap_serve_cwmp__TransferComplete(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Kicked"))
		return soap_serve_cwmp__Kicked(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:RequestDownload"))
		return soap_serve_cwmp__RequestDownload(soap);
#ifdef AEI_TR69
  soap_Unknown_Method_fault(soap);
#endif
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetRPCMethods(struct soap *soap)
{	struct cwmp__GetRPCMethods soap_tmp_cwmp__GetRPCMethods;
	struct _cwmp__GetRPCMethodsResponse __GetRPCMethodsResponse;
	soap_default__cwmp__GetRPCMethodsResponse(soap, &__GetRPCMethodsResponse);
	soap_default_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods, "cwmp:GetRPCMethods", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetRPCMethods(soap, &__GetRPCMethodsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetRPCMethodsResponse(soap, &__GetRPCMethodsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetRPCMethodsResponse(soap, &__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetRPCMethodsResponse(soap, &__GetRPCMethodsResponse, "cwmp:GetRPCMethodsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterValues(struct soap *soap)
{	struct cwmp__SetParameterValues soap_tmp_cwmp__SetParameterValues;
	struct _cwmp__SetParameterValuesResponse __SetParameterValuesReponse;
	soap_default__cwmp__SetParameterValuesResponse(soap, &__SetParameterValuesReponse);
	soap_default_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues, "cwmp:SetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__SetParameterValues(soap, soap_tmp_cwmp__SetParameterValues.__SetParameterValues, &__SetParameterValuesReponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__SetParameterValuesResponse(soap, &__SetParameterValuesReponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetParameterValuesResponse(soap, &__SetParameterValuesReponse, "cwmp:SetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetParameterValuesResponse(soap, &__SetParameterValuesReponse, "cwmp:SetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterValues(struct soap *soap)
{	struct cwmp__GetParameterValues soap_tmp_cwmp__GetParameterValues;
	struct _cwmp__GetParameterValuesResponse __GetParameterValuesResponse;
	soap_default__cwmp__GetParameterValuesResponse(soap, &__GetParameterValuesResponse);
	soap_default_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues, "cwmp:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
        soap->error = cwmp__GetParameterValues(soap, soap_tmp_cwmp__GetParameterValues.__GetParameterValues, &__GetParameterValuesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterValuesResponse(soap, &__GetParameterValuesResponse);

        if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterValuesResponse(soap, &__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

        soap->userid = global_tr69_info.tr69_acs_username;
        soap->passwd = global_tr69_info.tr69_acs_password;

        soap_connect(soap, global_acs_server, "");
        //---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterValuesResponse(soap, &__GetParameterValuesResponse, "cwmp:GetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
            || soap_end_send(soap)
            )
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterNames(struct soap *soap)
{	struct cwmp__GetParameterNames soap_tmp_cwmp__GetParameterNames;
	struct _cwmp__GetParameterNamesResponse __GetParameterNamesResponse;
	soap_default__cwmp__GetParameterNamesResponse(soap, &__GetParameterNamesResponse);
	soap_default_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames, "cwmp:GetParameterNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetParameterNames(soap, soap_tmp_cwmp__GetParameterNames.__GetParameterNames, &__GetParameterNamesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterNamesResponse(soap, &__GetParameterNamesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterNamesResponse(soap, &__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

        soap->userid = global_tr69_info.tr69_acs_username;
        soap->passwd = global_tr69_info.tr69_acs_password;

        soap_connect(soap, global_acs_server, "");
        //---add end---

	
	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterNamesResponse(soap, &__GetParameterNamesResponse, "cwmp:GetParameterNamesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterAttributes(struct soap *soap)
{	struct cwmp__SetParameterAttributes soap_tmp_cwmp__SetParameterAttributes;
	struct _cwmp__SetParameterAttributesResponse __SetParameterAttributesResponse;
	soap_default__cwmp__SetParameterAttributesResponse(soap, &__SetParameterAttributesResponse);
	soap_default_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__SetParameterAttributes(soap, soap_tmp_cwmp__SetParameterAttributes.__SetParameterAttributes, &__SetParameterAttributesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__SetParameterAttributesResponse(soap, &__SetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetParameterAttributesResponse(soap, &__SetParameterAttributesResponse, "cwmp:SetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetParameterAttributesResponse(soap, &__SetParameterAttributesResponse, "cwmp:SetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterAttributes(struct soap *soap)
{	struct cwmp__GetParameterAttributes soap_tmp_cwmp__GetParameterAttributes;
	struct _cwmp__GetParameterAttributesResponse __GetParameterAttributesResponse;
	soap_default__cwmp__GetParameterAttributesResponse(soap, &__GetParameterAttributesResponse);
	soap_default_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetParameterAttributes(soap, soap_tmp_cwmp__GetParameterAttributes.__GetParameterAttributes, &__GetParameterAttributesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetParameterAttributesResponse(soap, &__GetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetParameterAttributesResponse(soap, &__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetParameterAttributesResponse(soap, &__GetParameterAttributesResponse, "cwmp:GetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObject(struct soap *soap)
{	struct cwmp__AddObject soap_tmp_cwmp__AddObject;
	struct _cwmp__AddObjectResponse __AddObjectResponse;
	soap_default__cwmp__AddObjectResponse(soap, &__AddObjectResponse);
	soap_default_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject, "cwmp:AddObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__AddObject(soap, soap_tmp_cwmp__AddObject.__AddObject, &__AddObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__AddObjectResponse(soap, &__AddObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__AddObjectResponse(soap, &__AddObjectResponse, "cwmp:AddObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__AddObjectResponse(soap, &__AddObjectResponse, "cwmp:AddObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__DeleteObject(struct soap *soap)
{	struct cwmp__DeleteObject soap_tmp_cwmp__DeleteObject;
	struct _cwmp__DeleteObjectResponse __DeleteObjectResponse;
	soap_default__cwmp__DeleteObjectResponse(soap, &__DeleteObjectResponse);
	soap_default_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject, "cwmp:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__DeleteObject(soap, soap_tmp_cwmp__DeleteObject.__DeleteObject, &__DeleteObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__DeleteObjectResponse(soap, &__DeleteObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__DeleteObjectResponse(soap, &__DeleteObjectResponse, "cwmp:DeleteObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__DeleteObjectResponse(soap, &__DeleteObjectResponse, "cwmp:DeleteObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Download(struct soap *soap)
{	struct cwmp__Download soap_tmp_cwmp__Download;
	struct _cwmp__DownloadResponse __DownloadResponse;
	soap_default__cwmp__DownloadResponse(soap, &__DownloadResponse);
	soap_default_cwmp__Download(soap, &soap_tmp_cwmp__Download);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__Download(soap, &soap_tmp_cwmp__Download, "cwmp:Download", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;

	soap->error = cwmp__Download(soap, soap_tmp_cwmp__Download.__Download, &__DownloadResponse);

	if (soap->error)
		return soap->error;

	soap_serializeheader(soap);
	soap_serialize__cwmp__DownloadResponse(soap, &__DownloadResponse);
	if (soap_begin_count(soap))
		return soap->error;

	if (soap->mode & SOAP_IO_LENGTH)
	{
	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__DownloadResponse(soap, &__DownloadResponse, "cwmp:DownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__DownloadResponse(soap, &__DownloadResponse, "cwmp:DownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap)) {
		return soap->error;
	}
#ifdef AEI_TR69
  soap_closesock(soap);
  printf("TR69 Download and Upgrade ...... \n");

  return cwmp__Download_Upgrade(soap,
                  soap_tmp_cwmp__Download.__Download,
                  &__DownloadResponse);
  #else
  return soap_closesock(soap);
  #endif
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Reboot(struct soap *soap)
{	struct cwmp__Reboot soap_tmp_cwmp__Reboot;
	struct _cwmp__RebootResponse __RebootResponse;
	soap_default__cwmp__RebootResponse(soap, &__RebootResponse);
	soap_default_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot, "cwmp:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Reboot(soap, soap_tmp_cwmp__Reboot.__Reboot, &__RebootResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__RebootResponse(soap, &__RebootResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__RebootResponse(soap, &__RebootResponse, "cwmp:RebootResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__RebootResponse(soap, &__RebootResponse, "cwmp:RebootResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetQueuedTransfers(struct soap *soap)
{	struct cwmp__GetQueuedTransfers soap_tmp_cwmp__GetQueuedTransfers;
	struct _cwmp__GetQueuedTransfersResponse __GetQueuedTransfersResponse;
	soap_default__cwmp__GetQueuedTransfersResponse(soap, &__GetQueuedTransfersResponse);
	soap_default_cwmp__GetQueuedTransfers(soap, &soap_tmp_cwmp__GetQueuedTransfers);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__GetQueuedTransfers(soap, &soap_tmp_cwmp__GetQueuedTransfers, "cwmp:GetQueuedTransfers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetQueuedTransfers(soap, soap_tmp_cwmp__GetQueuedTransfers.__GetQueuedTransfers, &__GetQueuedTransfersResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetQueuedTransfersResponse(soap, &__GetQueuedTransfersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetQueuedTransfersResponse(soap, &__GetQueuedTransfersResponse, "cwmp:GetQueuedTransfersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetQueuedTransfersResponse(soap, &__GetQueuedTransfersResponse, "cwmp:GetQueuedTransfersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__ScheduleInform(struct soap *soap)
{	struct cwmp__ScheduleInform soap_tmp_cwmp__ScheduleInform;
	struct _cwmp__ScheduleInformResponse __ScheduleInformResponse;
	soap_default__cwmp__ScheduleInformResponse(soap, &__ScheduleInformResponse);
	soap_default_cwmp__ScheduleInform(soap, &soap_tmp_cwmp__ScheduleInform);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__ScheduleInform(soap, &soap_tmp_cwmp__ScheduleInform, "cwmp:ScheduleInform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__ScheduleInform(soap, soap_tmp_cwmp__ScheduleInform.__ScheduleInform, &__ScheduleInformResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__ScheduleInformResponse(soap, &__ScheduleInformResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__ScheduleInformResponse(soap, &__ScheduleInformResponse, "cwmp:ScheduleInformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__ScheduleInformResponse(soap, &__ScheduleInformResponse, "cwmp:ScheduleInformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetVouchers(struct soap *soap)
{	struct cwmp__SetVouchers soap_tmp_cwmp__SetVouchers;
	struct _cwmp__SetVouchersResponse __SetVouchersResponse;
	soap_default__cwmp__SetVouchersResponse(soap, &__SetVouchersResponse);
	soap_default_cwmp__SetVouchers(soap, &soap_tmp_cwmp__SetVouchers);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__SetVouchers(soap, &soap_tmp_cwmp__SetVouchers, "cwmp:SetVouchers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__SetVouchers(soap, soap_tmp_cwmp__SetVouchers.__SetVouchers, &__SetVouchersResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__SetVouchersResponse(soap, &__SetVouchersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__SetVouchersResponse(soap, &__SetVouchersResponse, "cwmp:SetVouchersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__SetVouchersResponse(soap, &__SetVouchersResponse, "cwmp:SetVouchersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetOptions(struct soap *soap)
{	struct cwmp__GetOptions soap_tmp_cwmp__GetOptions;
	struct _cwmp__GetOptionsResponse __GetOptionsResponse;
	soap_default__cwmp__GetOptionsResponse(soap, &__GetOptionsResponse);
	soap_default_cwmp__GetOptions(soap, &soap_tmp_cwmp__GetOptions);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__GetOptions(soap, &soap_tmp_cwmp__GetOptions, "cwmp:GetOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__GetOptions(soap, soap_tmp_cwmp__GetOptions.__GetOptions, &__GetOptionsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__GetOptionsResponse(soap, &__GetOptionsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__GetOptionsResponse(soap, &__GetOptionsResponse, "cwmp:GetOptionsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__GetOptionsResponse(soap, &__GetOptionsResponse, "cwmp:GetOptionsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Upload(struct soap *soap)
{	struct cwmp__Upload soap_tmp_cwmp__Upload;
	struct _cwmp__UploadResponse __UploadResponse;
	soap_default__cwmp__UploadResponse(soap, &__UploadResponse);
	soap_default_cwmp__Upload(soap, &soap_tmp_cwmp__Upload);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__Upload(soap, &soap_tmp_cwmp__Upload, "cwmp:Upload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Upload(soap, soap_tmp_cwmp__Upload.__Upload, &__UploadResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__UploadResponse(soap, &__UploadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__UploadResponse(soap, &__UploadResponse, "cwmp:UploadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__UploadResponse(soap, &__UploadResponse, "cwmp:UploadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__FactoryReset(struct soap *soap)
{	struct cwmp__FactoryReset soap_tmp_cwmp__FactoryReset;
	struct _cwmp__FactoryResetResponse __FactoryResetResponse;
	soap_default__cwmp__FactoryResetResponse(soap, &__FactoryResetResponse);
	soap_default_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset, "cwmp:FactoryReset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__FactoryReset(soap, soap_tmp_cwmp__FactoryReset.__FactoryReset, &__FactoryResetResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__FactoryResetResponse(soap, &__FactoryResetResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__FactoryResetResponse(soap, &__FactoryResetResponse, "cwmp:FactoryResetResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__FactoryResetResponse(soap, &__FactoryResetResponse, "cwmp:FactoryResetResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap *soap)
{	struct cwmp__Inform soap_tmp_cwmp__Inform;
	struct _cwmp__InformResponse __InformResponse;
	soap_default__cwmp__InformResponse(soap, &__InformResponse);
	soap_default_cwmp__Inform(soap, &soap_tmp_cwmp__Inform);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__Inform(soap, &soap_tmp_cwmp__Inform, "cwmp:Inform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Inform(soap, soap_tmp_cwmp__Inform.__Inform, &__InformResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__InformResponse(soap, &__InformResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__InformResponse(soap, &__InformResponse, "cwmp:InformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__InformResponse(soap, &__InformResponse, "cwmp:InformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__TransferComplete(struct soap *soap)
{	struct cwmp__TransferComplete soap_tmp_cwmp__TransferComplete;
	struct _cwmp__TransferCompleteResponse __TransferCompleteResponse;
	soap_default__cwmp__TransferCompleteResponse(soap, &__TransferCompleteResponse);
	soap_default_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete, "cwmp:TransferComplete", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__TransferComplete(soap, soap_tmp_cwmp__TransferComplete.__TransferComplete, &__TransferCompleteResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__TransferCompleteResponse(soap, &__TransferCompleteResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__TransferCompleteResponse(soap, &__TransferCompleteResponse, "cwmp:TransferCompleteResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__TransferCompleteResponse(soap, &__TransferCompleteResponse, "cwmp:TransferCompleteResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Kicked(struct soap *soap)
{	struct cwmp__Kicked soap_tmp_cwmp__Kicked;
	struct _cwmp__KickedResponse __KickedResponse;
	soap_default__cwmp__KickedResponse(soap, &__KickedResponse);
	soap_default_cwmp__Kicked(soap, &soap_tmp_cwmp__Kicked);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__Kicked(soap, &soap_tmp_cwmp__Kicked, "cwmp:Kicked", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__Kicked(soap, soap_tmp_cwmp__Kicked.__Kicked, &__KickedResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__KickedResponse(soap, &__KickedResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__KickedResponse(soap, &__KickedResponse, "cwmp:KickedResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__KickedResponse(soap, &__KickedResponse, "cwmp:KickedResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__RequestDownload(struct soap *soap)
{	struct cwmp__RequestDownload soap_tmp_cwmp__RequestDownload;
	struct _cwmp__RequestDownloadResponse __RequestDownloadResponse;
	soap_default__cwmp__RequestDownloadResponse(soap, &__RequestDownloadResponse);
	soap_default_cwmp__RequestDownload(soap, &soap_tmp_cwmp__RequestDownload);
	soap->encodingStyle = NULL;
	if (!soap_get_cwmp__RequestDownload(soap, &soap_tmp_cwmp__RequestDownload, "cwmp:RequestDownload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = cwmp__RequestDownload(soap, soap_tmp_cwmp__RequestDownload.__RequestDownload, &__RequestDownloadResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp__RequestDownloadResponse(soap, &__RequestDownloadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp__RequestDownloadResponse(soap, &__RequestDownloadResponse, "cwmp:RequestDownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};

	//---add ---
	soap_closesock(soap);

	soap->userid = global_tr69_info.tr69_acs_username;
	soap->passwd = global_tr69_info.tr69_acs_password;

	soap_connect(soap, global_acs_server, "");
	//---add end---

	if (soap_end_count(soap)
	    //--del--|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp__RequestDownloadResponse(soap, &__RequestDownloadResponse, "cwmp:RequestDownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
