all:
	make -C libxml
	make -C base64
	make -C expat
#	make -C dbus
	make -C zlib
	make -C gsoap2
	make -C dns

clean:
	make -C libxml clean
	make -C base64 clean
	make -C expat clean
#	make -C dbus clean
	make -C zlib clean
	make -C gsoap2 clean
	make -C dns clean
