#!/bin/sh

ifconfig lo 127.0.0.1

CINIT=1

hostname rlx-linux

mount -t proc proc /proc
mount -t ramfs ramfs /var

mkdir /var/tmp
mkdir /var/web
mkdir /var/log
mkdir /var/run
mkdir /var/lock
mkdir /var/system
mkdir /var/dnrd
mkdir /var/lib
mkdir /var/lib/misc

##For miniigd
mkdir /var/linuxigd
cp /etc/tmp/pics* /var/linuxigd 2>/dev/null

##For pptp
mkdir /var/ppp
mkdir /var/ppp/peers

#smbd
mkdir /var/config
mkdir /var/private
mkdir /var/tmp/usb

#snmpd
mkdir /var/net-snmp

cp /bin/pppoe.sh /var/ppp/true
echo "#!/bin/sh" > /var/ppp/true
#echo "PASS"     >> /var/ppp/true

#for console login
cp /etc/shadow.sample /var/shadow

#extact web pages
cd /web
flash extr /web
cd /
 
mkdir -p /var/udhcpc
mkdir -p /var/udhcpd
cp /bin/init.sh /var/udhcpc/eth0.deconfig
echo " " > /var/udhcpc/eth0.deconfig
cp /bin/init.sh /var/udhcpc/eth1.deconfig
echo " " > /var/udhcpc/eth1.deconfig
cp /bin/init.sh /var/udhcpc/br0.deconfig
echo " " > /var/udhcpc/br0.deconfig
cp /bin/init.sh /var/udhcpc/wlan0.deconfig
echo " " > /var/udhcpc/wlan0.deconfig

/bin/mount /dev/mtdblock4 /mnt/rt_conf/ -t jffs2 2>/dev/null
if [ -z "$(mount | grep "mtdblock4")" ]; then
	/sbin/flash_erase /dev/mtd4 0 32
	/bin/mount /dev/mtdblock4 /mnt/rt_conf/ -t jffs2
fi

if [ "$CINIT" = 1 ]; then
startup.sh
fi

# for wapi certs related
mkdir /var/myca
# wapi cert(must done before init.sh)
cp -rf /usr/local/ssl/* /var/myca/ 2>/dev/null
# loadWapiFiles >/dev/null 2>&1
 
# for wireless client mode 802.1x
mkdir /var/1x
cp -rf /usr/1x/* /var/1x/ 2>/dev/null
 
# Start system script
# init.sh gw all
init.sh aei mac
flash rescure_wsc_pin

# Start clinkd to initialize MOCA
#ifconfig clink0 && clinkd -Dvtf /etc/clink.conf --microcode /etc/EN2510.1.08.02.21_dic_gphy.bin --firmware /etc/EN2510.1.08.02.21_soc.bin clink0 &
 
# modify dst-cache setting
echo "8192" > /proc/sys/net/ipv4/route/max_size
echo "180" > /proc/sys/net/ipv4/route/gc_thresh
echo 20 > /proc/sys/net/ipv4/route/gc_elasticity
echo 35 > /proc/sys/net/ipv4/route/gc_interval
echo 60 > /proc/sys/net/ipv4/route/secret_interval
echo 10 > /proc/sys/net/ipv4/route/gc_timeout
 
# echo "4096" > /proc/sys/net/nf_conntrack_max
echo "4096" > /proc/sys/net/netfilter/nf_conntrack_max
echo "600" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established
echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait
echo "20" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_close
echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
echo "120" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream
echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout
echo "1048576" > /proc/sys/net/ipv4/rt_cache_rebuild_count
echo "32" > /proc/sys/net/netfilter/nf_conntrack_expect_max

echo 1 > /proc/sys/net/ipv4/ip_forward
#echo 2048 > /proc/sys/net/core/hot_list_length

#echo "run tr69_cfg ...."
#mkdir -p /var/rt_conf
#tr69_cfg /etc/protype.xml /etc/cfg.xml /etc/cfg.xml /tmp/cfg.xml
#sleep 1
mkdir -p /tmp/run

tr69 &
sleep 1
ssd &
data_center &
mynetwork &
# start web server
webs&
# start remote login server
#telnetd&
# start dropbear ssh server
makedevs pts
mount devpts /dev/pts -t devpts
#/usr/sbin/dropbear -p 22

# start checkntp script if /mnt/rt_conf/firstuse is not exist
# disable for enable or disable ntpclient by tr now
#[ ! -f /mnt/rt_conf/firstuse ] && echo UTC-0 > /tmp/TZ && /sbin/checkntp &
#/etc/watchdog &
/etc/watchdog_datacenter &

